// data-pipeline/buildMarketGap.js
//
// Derives the market-gap figures the Risk Lab publishes, from the graded
// record they claim to describe, and writes them to src/data/marketGap.json.
//
// These used to be constants typed into src/utils/marketGap.js by hand, with a
// test pinning them to the record. That caught drift, but only ever on the NEXT
// pull request - and it caught it there whether or not that PR had anything to
// do with the figures. A refresh on 2026-08-21 regenerated track_record.json
// with the match-identity dedupe applied, every figure moved, and the failure
// surfaced on an unrelated parlay change hours later. The published claim was
// wrong on the live site for the whole of that gap.
//
// So they are derived instead. `prebuild` runs this before every `vite build`,
// which means the deployed bundle is always computed from the data in the same
// commit: a stale figure is no longer possible to ship, rather than merely
// possible to detect. The refresh workflow runs it too, so the committed file
// tracks the data and the change is visible in the diff.
//
// Run: npm run build-market-gap
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const TRACK = path.join(ROOT, 'public', 'data', 'track_record.json');
const OUT = path.join(ROOT, 'src', 'data', 'marketGap.json');

// Kept in step with src/utils/marketGap.js, which owns the window itself. The
// bands are a product decision; this file only measures them.
const GAP_FLOOR = 0.10;
const GAP_CEIL = 0.20;

// Bookmaker-implied probability for OUR pick, vig removed.
function marketProbOf(row) {
  const o1 = Number(row.od1), o2 = Number(row.od2);
  if (!(o1 > 1) || !(o2 > 1)) return null;
  const q1 = 1 / o1, q2 = 1 / o2;
  const p1 = q1 / (q1 + q2);
  return row.favorite === row.p1 ? p1 : 1 - p1;
}

const { rowNoCall, FALLBACK: CALL_THRESHOLD } = require('./lib/noCall');

function bandStats(rows, lo, hi) {
  const inBand = [];
  for (const r of rows) {
    const mk = marketProbOf(r);
    if (mk == null || typeof r.favProb !== 'number' || typeof r.correct !== 'boolean') continue;
    // Calls only - a coin flip under its cell's threshold is not a claim, so
    // it cannot be evidence for one. Same rule as src/utils/marketGap.js,
    // and per tour x surface: a single global compare here would readmit
    // WTA clay coin flips (cutoff 0.64) that the ledger excludes.
    if (rowNoCall(r)) continue;
    const gap = r.favProb - mk;
    if (gap >= lo && gap < hi) inBand.push({ r, mk });
  }
  if (!inBand.length) return { n: 0, hitRate: null, marketImplied: null, stated: null };
  const mean = (f) => inBand.reduce((s, x) => s + f(x), 0) / inBand.length;
  return {
    n: inBand.length,
    hitRate: mean((x) => (x.r.correct ? 1 : 0)),
    marketImplied: mean((x) => x.mk),
    stated: mean((x) => x.r.favProb),
  };
}

function build() {
  if (!fs.existsSync(TRACK)) {
    // Refusing beats writing zeros: a figure of 0% would read as a real
    // measurement on the page rather than as missing data.
    console.error(`buildMarketGap: ${path.relative(ROOT, TRACK)} not found; refusing to write.`);
    process.exit(1);
  }
  const rows = (JSON.parse(fs.readFileSync(TRACK, 'utf8')).matches || [])
    .filter((r) => r && r.winner);
  const priced = rows.filter((r) => marketProbOf(r) != null && typeof r.correct === 'boolean');
  const band = bandStats(rows, GAP_FLOOR, GAP_CEIL);
  const beyond = bandStats(rows, GAP_CEIL, 1);

  if (!band.n) {
    console.error('buildMarketGap: no graded priced rows fall in the band; refusing to write.');
    process.exit(1);
  }

  const round = (x, d = 4) => (x == null ? null : Number(x.toFixed(d)));
  const out = {
    _comment: 'GENERATED by data-pipeline/buildMarketGap.js. Do not edit; run npm run build-market-gap.',
    measuredAt: new Date().toISOString().slice(0, 10),
    gapFloor: GAP_FLOOR,
    gapCeil: GAP_CEIL,
    gapCallThreshold: CALL_THRESHOLD,
    band: {
      pricedGraded: priced.length,
      n: band.n,
      hitRate: round(band.hitRate),
      marketImplied: round(band.marketImplied),
      stated: round(band.stated),
    },
    beyondCeil: {
      n: beyond.n,
      hitRate: round(beyond.hitRate),
      stated: round(beyond.stated),
    },
  };

  // Only rewrite when something other than the date moved, so a build does not
  // produce a spurious one-line diff on every run.
  const same = fs.existsSync(OUT) && (() => {
    const prev = JSON.parse(fs.readFileSync(OUT, 'utf8'));
    return JSON.stringify({ ...prev, measuredAt: null }) === JSON.stringify({ ...out, measuredAt: null });
  })();
  if (same) {
    console.log(`market gap: unchanged (band n=${out.band.n}, hit ${(out.band.hitRate * 100).toFixed(1)}%)`);
    return;
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, `${JSON.stringify(out, null, 2)}\n`);
  console.log(
    `market gap -> ${path.relative(ROOT, OUT)}  priced ${out.band.pricedGraded}, `
    + `band n=${out.band.n} hit ${(out.band.hitRate * 100).toFixed(1)}% vs market `
    + `${(out.band.marketImplied * 100).toFixed(1)}%, beyond n=${out.beyondCeil.n} `
    + `hit ${(out.beyondCeil.hitRate * 100).toFixed(1)}%`
  );
}

if (require.main === module) build();
module.exports = { build, bandStats, marketProbOf, GAP_FLOOR, GAP_CEIL };
