// Pins the market-gap figures the Parlay builder PUBLISHES to the graded
// record they claim to describe.
//
// This exists because the page said those calls "came in 69% of the time" when
// the record said 55% - a 14-point overstatement that survived only because
// the number was typed into a sentence and never rechecked. Any claim about
// our own record should fail the build when it drifts, not sit there being
// wrong. Tolerances are one rounding step, since the copy shows whole percent.
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { BAND, BEYOND_CEIL, GAP_FLOOR, GAP_CEIL, bandStats, marketProbOf } from './marketGap';
import FIGURES from '../data/marketGap.json';

const track = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), 'public/data/track_record.json'), 'utf8')
);
const rows = track.matches;
const priced = rows.filter((r) => marketProbOf(r) != null && typeof r.correct === 'boolean');

describe('the published market-gap figures match the record', () => {
  // These are DERIVED now (data-pipeline/buildMarketGap.js -> src/data/
  // marketGap.json, regenerated by prebuild), so the question is no longer
  // "is the typed number close enough" but "was the file regenerated against
  // the record sitting next to it". That makes these exact rather than
  // tolerant: any drift at all means the generator did not run.
  const s = bandStats(rows);
  const beyond = bandStats(rows, GAP_CEIL, 1);
  const near = (a, b) => expect(Math.abs(a - b)).toBeLessThan(5e-5);

  it('was regenerated against the record it ships with', () => {
    expect(BAND.pricedGraded).toBe(priced.length);
    expect(BAND.n).toBe(s.n);
    near(BAND.hitRate, s.hitRate);
    near(BAND.marketImplied, s.marketImplied);
    near(BAND.stated, s.stated);
    expect(BEYOND_CEIL.n).toBe(beyond.n);
    near(BEYOND_CEIL.hitRate, beyond.hitRate);
    near(BEYOND_CEIL.stated, beyond.stated);
  });

  it('was generated with the same gap window the module applies', () => {
    // The generator is CommonJS in data-pipeline and cannot import this ESM
    // module, so the window is duplicated. If the two ever drift, the figures
    // would describe a different band from the one the page selects matches
    // with - and both halves would look internally consistent.
    expect(FIGURES.gapFloor).toBe(GAP_FLOOR);
    expect(FIGURES.gapCeil).toBe(GAP_CEIL);
  });

  it('describes a sample big enough to quote', () => {
    // A band of a dozen matches would be noise dressed up as a record.
    expect(s.n).toBeGreaterThan(50);
    expect(priced.length).toBeGreaterThan(500);
    expect(priced.length).toBeLessThanOrEqual(rows.length);
  });

  it('still shows a real edge over the market in that band', () => {
    // The whole reason the builder suggests from this band. If this ever
    // fails, the suggestion needs removing, not renumbering.
    expect(s.hitRate).toBeGreaterThan(s.marketImplied);
  });

  it('agrees that past the ceiling the model is wrong, not brave', () => {
    // The claim that justifies having a ceiling at all: stated confidence
    // runs well ahead of what those calls actually did.
    expect(beyond.stated).toBeGreaterThan(beyond.hitRate);
  });

  it('the ceiling band really is worse than the suggested band', () => {
    expect(s.hitRate).toBeGreaterThan(beyond.hitRate);
  });
});

describe('marketProbOf', () => {
  it('strips the vig and orients to our pick', () => {
    // Even prices: both sides 50% after the vig comes out.
    expect(marketProbOf({ od1: 2, od2: 2, favorite: 'a', p1: 'a' })).toBeCloseTo(0.5, 9);
    // Short price on p1, and we favour p1.
    const p = marketProbOf({ od1: 1.5, od2: 3, favorite: 'a', p1: 'a' });
    expect(p).toBeCloseTo(2 / 3, 9);
    // Same row, but our pick is the other side.
    expect(marketProbOf({ od1: 1.5, od2: 3, favorite: 'b', p1: 'a' })).toBeCloseTo(1 / 3, 9);
  });

  it('returns null without a usable price', () => {
    expect(marketProbOf({ od1: null, od2: 2, favorite: 'a', p1: 'a' })).toBeNull();
    expect(marketProbOf({ od1: 1, od2: 2, favorite: 'a', p1: 'a' })).toBeNull();
  });
});

describe('the gap window itself', () => {
  it('has a floor and a ceiling, in that order', () => {
    expect(GAP_FLOOR).toBeGreaterThan(0);
    expect(GAP_CEIL).toBeGreaterThan(GAP_FLOOR);
  });

  it('flagging any gap at all would be close to meaningless', () => {
    // The justification for having a floor: it fires on about half the card.
    const anyGap = priced.filter((r) => r.favProb - marketProbOf(r) > 0);
    const share = anyGap.length / priced.length;
    expect(share).toBeGreaterThan(0.4);
    expect(share).toBeLessThan(0.7);
  });
});
