// The no-call contract. A match whose stated probability sits below
// engineConfig.callThreshold is a coin flip: we do not call it, we do not
// stake it, and no published claim counts it in either direction. The lean
// is still recorded and still graded, as an audit of the restraint.
//
// These pin the behaviors that must not drift apart, because
// excluded-by-negation is this repo's documented bug class. Two live
// examples, both caught by hand rather than by a test, which is why the
// coverage below is shaped the way it is:
//
//   - `!row.noCall` was the ledger filter, and NO ledger row carried the
//     flag. Every one of the 278 graded rows, including 74 coin flips, sailed
//     through a filter that looked correct and did nothing.
//   - The season benchmark counted hits over EVERY graded row and divided by
//     calls only, publishing 94% against a true 72%.
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import CONFIG from './engineConfig.json';
import { pickNoCall, ledgerNoCall, CALL_THRESHOLD, CALL_THRESHOLDS, thresholdFor } from './utils/deployedPick';

const read = (p) => fs.readFileSync(path.join(process.cwd(), p), 'utf8');
const json = (p) => JSON.parse(read(p));

describe('the no-call threshold', () => {
  it('exists, is a coin-flip band, and stays below the leans tier', () => {
    expect(CONFIG.callThreshold).toBeGreaterThan(0.5);
    expect(CONFIG.callThreshold).toBeLessThanOrEqual(0.65);
    expect(CALL_THRESHOLD).toBe(CONFIG.callThreshold);
  });

  it('is applied at lock time in buildPredictions', () => {
    const src = read('data-pipeline/buildPredictions.js');
    expect(src).toMatch(/favProb < \(ENGINE\.callThreshold \|\| 0\)/);
    expect(src).toMatch(/noCall: true/);
  });
});

describe('the rule is DERIVED, never trusted from the stored flag', () => {
  // The flag is written prospectively and only against the threshold in
  // force that day, so a filter that reads it alone silently passes the
  // whole back history. Both accessors must fall back to the probability.
  it('a ledger row under its cell threshold is a no-call with no flag present', () => {
    const T = thresholdFor('atp', 'hard');
    expect(ledgerNoCall({ tour: 'atp', surface: 'hard', favProb: T - 0.01 })).toBe(true);
    expect(ledgerNoCall({ tour: 'atp', surface: 'hard', favProb: T + 0.01 })).toBe(false);
    expect(ledgerNoCall({ tour: 'atp', surface: 'hard', favProb: 0.99, noCall: true })).toBe(true);
  });

  it('a track row under its cell threshold is a no-call from its deployed pick', () => {
    const T = thresholdFor('atp', 'hard');
    const under = 1 - (T - 0.01); // oriented to p1, favourite is p2
    expect(pickNoCall({ tour: 'atp', surface: 'hard', pickProbP1: under })).toBe(true);
    expect(pickNoCall({ tour: 'atp', surface: 'hard', pickProbP1: T + 0.01 })).toBe(false);
  });

  it('the cutoff varies by cell, and unknown cells fall back to the default', () => {
    // The whole point of the table: one number cannot be right for both of
    // these. If they ever collapse to equal, either the tuner has stopped
    // running or the evidence really did converge - check before deleting.
    expect(thresholdFor('atp', 'clay')).not.toBe(thresholdFor('wta', 'clay'));
    expect(thresholdFor('nope', 'nope')).toBe(CONFIG.callThreshold);
    for (const T of Object.values(CALL_THRESHOLDS.cells)) {
      expect(T).toBeGreaterThanOrEqual(CALL_THRESHOLDS.clamp[0]);
      expect(T).toBeLessThanOrEqual(CALL_THRESHOLDS.clamp[1]);
    }
  });

  // How far a published cutoff may sit from what the CURRENT record derives.
  //
  // This used to demand byte-equality, which quietly asserted something the
  // design never promised. The cutoffs are regenerated by the tuner four
  // times a year, before each slam, deliberately: the rule for what counts as
  // a call should not move under an event while that event is being graded.
  // But `refresh-data` rewrites track_record.json every day of a slam, so the
  // re-derived value moves daily and the equality check went red a few days
  // into every tournament - on a schedule, without a commit to blame.
  //
  // A tolerance keeps what the test was actually for (its own comment: "a
  // hand-edit to callThresholds.json fails here" - a typed 0.75 or 0.40 is
  // nowhere near the sweep) and drops the freshness demand that was never
  // real. Staleness is checked directly below instead, where it can say so.
  const DRIFT_TOLERANCE = 0.05;

  it('every cell threshold is still justified by the record it was fitted on', () => {
    // Re-derives each published cutoff from track_record.json with the
    // tuner's own rule.
    //
    // The sweep is not the last word. When the hindsight guard fails - the
    // bookmakers' prices calibrating differently across our own call/no-call
    // split, which they cannot do on outcome-blind data - no cutoff is
    // allowed below the global default, because the contamination makes
    // marginal bands look better than they are and so pushes the sweep DOWN.
    const { cellThreshold } = require('../data-pipeline/tuneCallThreshold');
    const rows = JSON.parse(read('public/data/track_record.json')).matches || [];
    const guardFailed = CALL_THRESHOLDS.hindsightGuard?.passed === false;
    for (const [key, T] of Object.entries(CALL_THRESHOLDS.cells)) {
      const [tour, surface] = key.split('|');
      const cell = rows.filter((m) => m.tour === tour && m.surface === surface);
      const raw = cellThreshold(cell);
      let expected = Math.min(CALL_THRESHOLDS.clamp[1], Math.max(CALL_THRESHOLDS.clamp[0], raw));
      if (guardFailed) expected = Math.max(expected, CONFIG.callThreshold);
      // eslint-disable-next-line jest/valid-expect
      expect(Math.abs(T - expected), `${key}: published ${T}, record now derives ${expected}`)
        .toBeLessThanOrEqual(DRIFT_TOLERANCE + 1e-9);
    }
  });

  it('the tuner has run recently enough for those cutoffs to mean anything', () => {
    // The freshness guarantee, stated on its own so a failure says which
    // problem it is. Byte-equality used to enforce this by accident, and
    // reported it as a mismatched number rather than as "re-run the tuner".
    // Four scheduled retunes a year, plus manual dispatches, so a gap past
    // five months means the tuner has stopped running.
    const measured = new Date(CALL_THRESHOLDS.measuredAt);
    expect(Number.isNaN(measured.getTime())).toBe(false);
    const days = (Date.now() - measured.getTime()) / 86400000;
    // eslint-disable-next-line jest/valid-expect
    expect(days, `callThresholds.json was measured ${Math.round(days)} days ago; re-run data-pipeline/tuneCallThreshold.js --write`)
      .toBeLessThan(150);
  });

  it('the live ledger actually contains rows the flag alone would miss', () => {
    // Regression guard for the incident itself. If this ever reaches zero
    // because the pipeline backfilled the flag, the derivation is still
    // correct - but until then it is the only thing excluding them.
    const rows = (json('public/data/predictions.json').predictions || [])
      .filter((p) => p.status === 'won' || p.status === 'lost');
    const derived = rows.filter(ledgerNoCall).length;
    const flagged = rows.filter((p) => p.noCall === true).length;
    expect(derived).toBeGreaterThanOrEqual(flagged);
  });
});

describe('headline surfaces count calls only', () => {
  const rows = [
    { status: 'won', correct: true, favProb: 0.8 },
    { status: 'lost', correct: false, favProb: 0.8 },
    { status: 'won', correct: true, favProb: 0.52 }, // coin flip: not a call
    { status: 'void', correct: false, favProb: 0.8 },
  ];
  const decided = rows.filter((p) => (p.status === 'won' || p.status === 'lost') && !ledgerNoCall(p));

  it('a graded no-call never enters the forward record', () => {
    expect(decided.length).toBe(2);
    expect(decided.filter((p) => p.correct).length).toBe(1);
  });

  it('every headline consumer derives the exclusion instead of reading the flag', () => {
    for (const f of [
      // The builder's own copy of this filter moved into useTodayCard when the
      // risk lab was folded into the page: one loader for the staking
      // surfaces, so there is one population rather than two that can drift.
      'src/pages/Home.js', 'src/pages/TrackRecord.js', 'src/utils/useTodayCard.js',
      'data-pipeline/buildDigest.js', 'data-pipeline/buildShareAssets.js',
      'data-pipeline/checkGuardrails.js', 'data-pipeline/sendPush.js',
    ]) {
      const src = read(f);
      expect(`${f} uses ledgerNoCall: ${/ledgerNoCall/.test(src)}`).toBe(`${f} uses ledgerNoCall: true`);
      // The bare-flag filter is the bug. It must not come back.
      expect(`${f} has bare !p.noCall: ${/&& !p(r)?\.noCall\b/.test(src)}`).toBe(`${f} has bare !p.noCall: false`);
    }
  });

  it('a numerator is never counted over a wider population than its denominator', () => {
    // The 94%-vs-72% incident: deployedCorrect came off `filtered` (all
    // graded rows) while `n` came off `filteredCalls`.
    const src = read('src/pages/TrackRecord.js');
    expect(src).toMatch(/const deployedCorrect = filteredCalls\.filter/);
  });
});

describe('the staking universe is calls only', () => {
  // Reversed on 2026-08-23. The builder used to price no-calls on the
  // reasoning that it bets edges rather than calls; a product that declines
  // to claim a coin flip and then asks you to stake one says two things at
  // once, so the two now agree.
  it('the shared card loader filters the whole ledger before anything is built', () => {
    const src = read('src/utils/useTodayCard.js');
    expect(src).toMatch(/\(d\.predictions \|\| \[\]\)\.filter\(\(p\) => !ledgerNoCall\(p\)\)/);
  });

  it('the builder and the risk lab load the card from that one place', () => {
    // They used to be two pages with two copies of the same forty lines, which
    // is two chances to price different populations on the same day.
    const src = read('src/pages/Parlay.js');
    expect(src).toMatch(/useTodayCard/);
    expect(src).not.toMatch(/d\.predictions/);
  });

  it('plan settlement excludes them at the shared seam', () => {
    const src = read('data-pipeline/lib/planSettle.js');
    expect(src).toMatch(/function ledgerGraded[\s\S]*?!ledgerNoCall\(m\)/);
  });

  it('the home plan card and the builder read the same population', () => {
    const src = read('src/pages/Home.js');
    expect(src).toMatch(/const pending = all\.filter\(\(p\) => p\.status === 'pending' && !ledgerNoCall\(p\)\)/);
    expect(src).toMatch(/const card = pending\.filter/);
  });

  it('the policy tournament scores the universe the builder actually prices', () => {
    expect(read('data-pipeline/expPlanPolicies.js')).toMatch(/!rowNoCall\(m\)/);
  });
});

describe('the retrospective record speaks the same policy', () => {
  it('pickNoCall derives from the deployed probability and the cell threshold', () => {
    const src = read('src/utils/deployedPick.js');
    expect(src).toMatch(/pickNoCall = \(m\) => pickFavProb\(m\) < thresholdFor\(m\.tour, m\.surface\)/);
  });

  it('every retrospective claim surface mirrors the rule', () => {
    const files = [
      'src/pages/Home.js', 'src/pages/TrackRecord.js', 'src/pages/Methodology.js',
      'src/pages/EdgeBoard.js', 'data-pipeline/buildDailyScorecard.js',
      'data-pipeline/buildDigest.js', 'data-pipeline/buildShareAssets.js',
      'data-pipeline/checkGuardrails.js', 'data-pipeline/buildMarketGap.js',
      'src/utils/marketGap.js',
    ];
    for (const f of files) {
      const src = read(f);
      const ok = /pickNoCall|rowNoCall|ledgerNoCall|callThreshold/.test(src);
      expect(`${f}: ${ok}`).toBe(`${f}: true`);
    }
  });

  it('the pipeline mirror and the browser rule agree on the same rows', () => {
    // One threshold, two runtimes. Sampled against the real record rather
    // than asserted by eye, because the CommonJS copy is the one that can
    // drift unnoticed.
    const { rowNoCall } = require('../data-pipeline/lib/noCall');
    const rows = (json('public/data/track_record.json').matches || []).slice(0, 800);
    for (const m of rows) expect(rowNoCall(m)).toBe(pickNoCall(m));
  });

  it('the exclusion is computed, never written onto track rows', () => {
    const rows = json('public/data/track_record.json').matches || [];
    expect(rows.filter((m) => m.noCall != null).length).toBe(0);
  });
});
